### ISSUE TITLE
got an unexpected keyword argument 'verbose'

### ISSUE THREAD

**Issue by mostafanorouzi** [LovelyBuggies/sumo-gym#70]
got an unexpected keyword argument 'verbose'
```
Traceback (most recent call last):
  File "tutorials/fmp-jumbo.py", line 11, in <module>
    env = gym.make(
  File "/home/mostafa/pyenv/py38/lib/python3.8/site-packages/gym/envs/registration.py", line 652, in make
    raise e
  File "/home/mostafa/pyenv/py38/lib/python3.8/site-packages/gym/envs/registration.py", line 640, in make
    env = env_creator(**_kwargs)
  File "/home/mostafa/pyenv/py38/lib/python3.8/site-packages/sumo_gym/envs/fmp.py", line 262, in __init__
    self._fmp = FMP(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'verbose'
```

**Comment by lumi232** [comment]
verbose support got dropped after python3.6

**Comment by Syfu11ah** [comment]
Was anyone able to run this? I am getting the same error. what are the system requirements?
